### ISSUE TITLE
Use CampaignClass in all Malaria Interventions

### ISSUE THREAD

**Issue by CWiswell-IDM** [InstituteforDiseaseModeling/dtk-tools-malaria#53]
@ZDu-IDM has created a campaign class to make interventions schema dependent. 

Each malaria intervention should consume this work.

We believe that all of the dtk-tools proper interventions are doing this, but that dtk-tools-malaria are not (necessarily)

**Comment by CWiswell-IDM** [comment]
Please assign @Sv3tlana

**Comment by Sv3tlana** [comment]
This is no longer a goal. 
Because of exe/schema differences between trunk and Malaria-Ongoing (and researchers' person branches) it seems it would be a hassle to maintain this if we switch to doing it via CampaignClass as CampaignClass would have to be regenerated for every new exe and the interventions might or might not have problems with it. 
It has been replaced with general clean up and improvement goals - a new ticket has been made: #67
